### ISSUE TITLE
feature request: deezer & bandlab support

### ISSUE THREAD

**Issue by MrCakeSlayer** [DuncteBot/skybot-lavalink-plugin#11]
Bandlab: https://www.bandlab.com/?lang=en
Deezer: https://www.deezer.com/us/
:)

**Comment by duncte123** [comment]
Could you link me examples of links to songs on bandlab? I can't seem to find anything for that.
For deezer I will give it the spotify treatment, it will need to search the songs on youtube

**Comment by duncte123** [comment]
Closing this issue as I did not get a reply to my request
