### ISSUE TITLE
Soundgasm incorrectly read duration.

### ISSUE THREAD

**Issue by zoli456** [DuncteBot/skybot-lavalink-plugin#17]
If you want to play from Soundgasm it display insanly high number.

**Comment by duncte123** [comment]
That is correct. I cannot extract the duration of the track so I am using the provided "CONTENT_LENGTH_UNKNOWN" constant as seen here: https://github.com/DuncteBot/skybot-source-managers/blob/master/src/main/java/com/dunctebot/sourcemanagers/soundgasm/SoundGasmAudioTrack.java#L31-L33
