### ISSUE TITLE
Support for Lavalink 4

### ISSUE THREAD

**Issue by zoli456** [DuncteBot/skybot-lavalink-plugin#20]
https://github.com/lavalink-devs/Lavalink/blob/master/CHANGELOG.md
They recently released the new Lavalink version and this plugin will need some changes to work with the new version.

**Comment by duncte123** [comment]
Indeed, was planning to work on that when I finish https://github.com/esamarathon/oengusio/pull/164

**Comment by duncte123** [comment]
Since lavalink 4 is still in BETA, you can download a pre-release version of the plugin here https://github.com/DuncteBot/skybot-lavalink-plugin/releases/tag/PRE_1.5.0_18
