### ISSUE TITLE
Some issues I have found

### ISSUE THREAD

**Issue by Spiderjockey02** [DuncteBot/skybot-lavalink-plugin#3]
## Description

- [ ] Reddit currently errors out due to `this video has no audio`.
- [ ] The 18+ video website errors out due to `Could not extract video url`.

## Version info
**Client used:** erela.js

Output of `java -version`:
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)
```

**Comment by duncte123** [comment]
Both of these issues have been resolved in version `1.1.3`
