### ISSUE TITLE
feature request: soundgasm.net source

### ISSUE THREAD

**Issue by DarrenOfficial** [DuncteBot/skybot-lavalink-plugin#5]
why? Soundgasm.net is an audio sharing platform used by https://reddit.com/r/gonewildaudio & r/vanillaaudio & many more

example of soundgasm https://soundgasm.net/u/not_your_habibTEA/My-Power-is-Out-Can-I-Come-In

**Comment by duncte123** [comment]
Well, that's certainly a request.

I'll have a look to see what I can do

**Comment by duncte123** [comment]
Implemented in version 1.4.0
