### ISSUE TITLE
Text To Speak doesn't seem to be working

### ISSUE THREAD

**Issue by Spiderjockey02** [DuncteBot/skybot-lavalink-plugin#8]
## Description
It appears the Text to Speak plugin isn't working I have tried `tts:SOME TEXT` and `speak:SOME TEXT` and both respond with `No matches found` and yes I have it enabled in the application.yml file
![image](https://user-images.githubusercontent.com/55885015/179394906-e4b93836-bcd9-4f44-b747-9c027b1bee69.png)

## Version info
**Client used:** erela.js

Output of `java -version`:
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```

Lavalink logs: [https://pastebin.com/WuexCSMC](https://pastebin.com/WuexCSMC)

**Comment by duncte123** [comment]
when you used `speak:text` the source manager was not enabled according to your logs
The source manager does not listen to `tts:`
